[versions]
project = "2.1.21"

kotlin = "2.1.21"
exportPublic = "2.1.21"

[libraries]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
exportPublic = { id = "net.akehurst.kotlin.gradle.plugin.exportPublic", version.ref = "exportPublic" }
